### PR TITLE
Improve watchlist

### LINKED ISSUE #10: Improve watchlist
User should be able to categorize it's watchlist in three section: finished, watching and aim to see. You could add these kind of buttons:

image

### PR DESCRIPTION
**Pull request by JurajVetrak**
Watchlist is improved i added 4 buttons at the top of watchlist also there is logic for filtering this shows in watchlist by them:
image
image

next i added options when you click on star there are two options if anime is in watchlist or not:
image

when anime is in watchlist you can change its category or remove it from there
image

at the end i added some animations for buttons when you hover over them and click them to indes.css:
image

### CODE REVIEW

**Comment by moonpatel** [comment]
Superb @JurajVetrak !! I like your work. Just two small changes:
1. remove the .idea directory from the commit.
2. Add the 'add bookmark' button on the anime details page too.

**Comment by JurajVetrak** [comment]
> Superb @JurajVetrak !! I like your work. Just two small changes:
> 
> 1. remove the .idea directory from the commit.
> 2. Add the 'add bookmark' button on the anime details page too.

i hope its okey now if there are some problems i will fix it

image
image

**Comment by moonpatel** [comment]
> > Superb @JurajVetrak !! I like your work. Just two small changes:
> > 
> > 1. remove the .idea directory from the commit.
> > 2. Add the 'add bookmark' button on the anime details page too.
> 
> i hope its okey now if there are some problems i will fix it
> 
> image image

Working fine @JurajVetrak ! I see that you have deleted BackEnd/.env.example file. Just include that again as it is important as a template for making the .env file. After that I will merge your PR.

**Comment by JurajVetrak** [comment]
> > > Superb @JurajVetrak !! I like your work. Just two small changes:
> > > 
> > > 1. remove the .idea directory from the commit.
> > > 2. Add the 'add bookmark' button on the anime details page too.
> > 
> > 
> > i hope its okey now if there are some problems i will fix it
> > image image
> 
> Working fine @JurajVetrak ! I see that you have deleted BackEnd/.env.example file. Just include that again as it is important as a template for making the .env file. After that I will merge your PR.

Done :)

**Comment by moonpatel** [comment]
Its .env.example not env.example @JurajVetrak

**Comment by JurajVetrak** [comment]
> Its .env.example not env.example @JurajVetrak

Sorry my bad i renamed it

**Comment by moonpatel** [comment]
> > Its .env.example not env.example @JurajVetrak
> 
> Sorry my bad i renamed it

Thanks for your contribution @JurajVetrak ! I am merging this PR now.

**Pull request merged**
