### PR TITLE
Added Styling to Logout button And Reckeck before login out

### PR DESCRIPTION
**Pull request by surajvast1**
Added Styling to Logout button And Reckeck before login out

image
image

### CODE REVIEW

**Comment by moonpatel** [comment]
Hey @surajvast1 you should use dark theme for the confirm logout modal as it matches more with the application.

**Comment by surajvast1** [comment]
Ohkkk I added Dark Mode Its Looks FIne Now I suppose
image

**Comment by surajvast1** [comment]
Can you merge this pr 
And if there anything else I am happy to contribute ☺️

**Comment by Peacexoom** [comment]
Hey, @surajvast1 the Reckeck before login out is too good but the styling to Logout button and username displaying section doesn't look that good so can you change those two back.

**Comment by surajvast1** [comment]
Ohk sure I'll change the logout button but I didn't understood the username what about it ?

**Comment by surajvast1** [comment]
Thanks I'll change them

**Comment by surajvast1** [comment]
Ohk  i changed It ,I  just added a small zoom in on button hover I hope it doen't creates problem I liked It better ,If any changes I am happy to contribute.
image

**Comment by surajvast1** [comment]
Ohk i changed It ,I just added a small zoom in on button hover I hope it doen't creates problem I liked It better ,If any changes I am happy to contribute.

image

**Comment by moonpatel** [comment]
Hey @surajvast1 it would be nice if you could use only tailwind css for the styling.

**Comment by Peacexoom** [comment]
> Hey @surajvast1 it would be nice if you could use only tailwind css for the styling.

Leave it's looking good. I am merging it.

**Pull request merged**
