### PR TITLE
Improved UI of login and signup page

### LINKED ISSUE #2: Improve UI of signup/login page

### PR DESCRIPTION
**Pull request by hardy07**
### Login Page
Screenshot (62)
### Signup Page
Screenshot (63)

### CODE REVIEW

**Comment by moonpatel** [comment]
Subarashi @hardy07 !!! Looks awesome. Just remove the .vscode directory and add that commit to this pr then I will merge it. Thanks for your contribution.

**Comment by Peacexoom** [comment]
Also, compress the image below 1 MB.

**Comment by Peacexoom** [comment]
By the way, @hardy07 it looks too good. Great work🙌

**Comment by hardy07** [comment]
All done. Thanks

**Comment by Peacexoom** [comment]
thank you for you contribution @hardy07.

**Pull request merged**
