### PR TITLE
Proper alignment + hover effect on genres

### PR DESCRIPTION
**Pull request by Pafestivo**
Added proper alignment to the bookmark options and added the hover effect from the login screen to the genres.
solving issue #41 

result:
image

### CODE REVIEW

**Comment by Peacexoom** [comment]
Hey @Pafestivo , I guess my description was not that much clear. Make the size of these genre buttons and hover effect just like this.
image
Also if possible can you remove the second commit.

**Comment by Pafestivo** [comment]
oh, got you - i was working on the left list of add bookmark.
for the following commit i fixed the layout and the hover effect as you said, but also kept the previous changes for the bookmark list. This is the new layout, I changed the alignment to the left, instead of center:
image
let me know if you wish to revert the bookmark list changes, it's not a problem.
waiting on your response! @Peacexoom

**Comment by Peacexoom** [comment]
Just change the size of genre buttons from py-1 to py-2 and i will merge your pr

**Comment by Pafestivo** [comment]
> Just change the size of genre buttons from py-1 to py-2 and i will merge your pr

Done, thanks for your patience.
Looking forward for more contribution opportunities.

**Comment by Peacexoom** [comment]
> Done, thanks for your patience. Looking forward for more contribution opportunities.

Sure, we are also looking forward for some great contributions. If you have any feature in mind we can discuss about that.

**Comment by Peacexoom** [comment]
Thanks for your contribution @Pafestivo

**Pull request merged**
