### PR TITLE
Added A search bar with Full functionality and changed Style accordingly 

### PR DESCRIPTION
**Pull request by surajvast1**

### CODE REVIEW

**Comment by surajvast1** [comment]
Screenshot from 2023-10-15 03-39-08

**Comment by surajvast1** [comment]
The functionality is working properly please merge this

**Comment by moonpatel** [comment]
> The functionality is working properly please merge this

You have removed the useEffect part of the code. It was not supposed to be removed.
The design of Search button looks good btw, you can keep that.
But discard the changes from Searchbar.jsx

**Comment by Peacexoom** [comment]
But do we need a search bar. Don't we have a dynamic search?

**Comment by surajvast1** [comment]
Ohkkk illl add the use effect again

**Comment by surajvast1** [comment]
hey @moonpatel See if we keep the use effect then on typing every word it gives somethiing which is not good as per the button method this is better way according .if you still feel that I should Add use Effect I am happy to remove it

**Comment by Peacexoom** [comment]
hey @surajvast1 , we have decided that instead of dynamic search we will use a search button.

**Comment by surajvast1** [comment]
So the work which I did would be merged

**Comment by Peacexoom** [comment]
Some suggestion:
- Remove the comments you have done
- Remove debounce things from the file(import and constant)
- Delete the debounce hook too.

You can refer to https://github.com/Peacexoom/AnimeHub/commit/bf00eef26e3a42e1b89da1e005ddaf9a4b3c184e

**Comment by Peacexoom** [comment]
> So the work which I did will be merged

Yesss

**Comment by surajvast1** [comment]
Yes Debounce Removed Any thing else i would love to contribute

**Comment by moonpatel** [comment]
> Yes Debounce Removed Any thing else i would love to contribute

Thanks for your contribution @surajvast1 !

**Pull request merged**
