### PR TITLE
Anime card made responsive

### LINKED ISSUE #4: Make anime card properly responsive
image

### PR DESCRIPTION
**Pull request by DarkSoul26**
### **Normal view:**

image

### **Mobile view:**

image

### CODE REVIEW

**Comment by Peacexoom** [comment]
What changes have you done in package-lock.json?

**Comment by Peacexoom** [comment]
Also the cards size has become varying.

**Comment by DarkSoul26** [comment]
So previously you can see the images in cards were not displayed in proper manner. 

Now, the cards are made responsive  according to the varying sizes of the images.

Also, I haven't changed anything in the package json file. Just npm install makes some changes automatically in it.

**Comment by Peacexoom** [comment]
> So previously you can see the images in cards were not displayed in proper manner.
> 
> Now, the cards are made responsive according to the varying sizes of the images.
> 
> Also, I haven't changed anything in the package json file. Just npm install makes some changes automatically in it.

Can you try to make the all the cards also of same size.

**Comment by DarkSoul26** [comment]
Sure

**Comment by DarkSoul26** [comment]
Hey @Peacexoom,
After some attempts I can surely say that cards when made of the same size doesn't look appropriate, as the images are of different sizes and therefore it includes some black border in some of the cards.

Current status:
https://github.com/Peacexoom/AnimeHub/assets/60578902/7f8e3f1b-928f-4190-b211-7c00bb1d74c7

**Comment by Peacexoom** [comment]
Sorry @DarkSoul26 but we wanted all the cards to be of same size and it has been done in pull request : https://github.com/Peacexoom/AnimeHub/pull/15

**Pull request closed without merging**
